"""Add availability models

Revision ID: 4c6f6798749b
Revises: 626387ad4afa
Create Date: 2025-11-17 13:07:26.171724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c6f6798749b'
down_revision: Union[str, Sequence[str], None] = '626387ad4afa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create recurring_availability table
    op.create_table(
        'recurring_availability',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('day_of_week', sa.Integer(), nullable=False),
        sa.Column('start_time_local', sa.Time(), nullable=False),
        sa.Column('end_time_local', sa.Time(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default='true'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name='valid_day'),
        sa.CheckConstraint('start_time_local < end_time_local', name='valid_time_order'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recurring_availability_id'), 'recurring_availability', ['id'], unique=False)
    op.create_index(
        'idx_recurring_availability_user',
        'recurring_availability',
        ['user_id'],
        postgresql_where=sa.text('enabled = TRUE')
    )

    # Create availability_blocks table
    op.create_table(
        'availability_blocks',
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('user_id', sa.BigInteger(), nullable=False),
        sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
        sa.Column('generated_from_recurring', sa.BigInteger(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
        sa.CheckConstraint('start_time < end_time', name='valid_order'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['generated_from_recurring'], ['recurring_availability.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'start_time', name='unique_user_time_slot')
    )
    op.create_index(op.f('ix_availability_blocks_id'), 'availability_blocks', ['id'], unique=False)
    op.create_index('idx_availability_blocks_user_time', 'availability_blocks', ['user_id', 'start_time'])
    op.create_index('idx_availability_blocks_time_range', 'availability_blocks', ['start_time', 'end_time'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_availability_blocks_time_range', table_name='availability_blocks')
    op.drop_index('idx_availability_blocks_user_time', table_name='availability_blocks')
    op.drop_index(op.f('ix_availability_blocks_id'), table_name='availability_blocks')
    op.drop_table('availability_blocks')

    op.drop_index('idx_recurring_availability_user', table_name='recurring_availability')
    op.drop_index(op.f('ix_recurring_availability_id'), table_name='recurring_availability')
    op.drop_table('recurring_availability')
    # ### end Alembic commands ###
