"""add_users_recurring_availability_and_blocks

Revision ID: 8fa7b5df7f3f
Revises: 
Create Date: 2025-11-17 12:42:31.734789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fa7b5df7f3f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('vacation_until', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('sms_consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(NOW())'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(NOW())'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('recurring_availability',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time_local', sa.Time(), nullable=False),
    sa.Column('end_time_local', sa.Time(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(NOW())'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(NOW())'), nullable=False),
    sa.CheckConstraint('day_of_week BETWEEN 1 AND 7', name='valid_day'),
    sa.CheckConstraint('start_time_local < end_time_local', name='valid_time_order'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recurring_availability_user', 'recurring_availability', ['user_id'], unique=False, postgresql_where=sa.text('enabled = TRUE'))
    op.create_index(op.f('ix_recurring_availability_id'), 'recurring_availability', ['id'], unique=False)
    op.create_table('availability_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('generated_from_recurring', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(NOW())'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('(NOW())'), nullable=False),
    # Note: INTERVAL constraint only works in PostgreSQL
    # sa.CheckConstraint("end_time = start_time + INTERVAL '30 minutes'", name='valid_duration'),
    sa.CheckConstraint('start_time < end_time', name='valid_order'),
    sa.ForeignKeyConstraint(['generated_from_recurring'], ['recurring_availability.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_availability_blocks_time_range', 'availability_blocks', ['start_time', 'end_time'], unique=False)
    op.create_index('idx_availability_blocks_user_time', 'availability_blocks', ['user_id', 'start_time'], unique=False)
    op.create_index(op.f('ix_availability_blocks_id'), 'availability_blocks', ['id'], unique=False)
    op.create_index('uq_availability_blocks_user_start', 'availability_blocks', ['user_id', 'start_time'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_availability_blocks_user_start', table_name='availability_blocks')
    op.drop_index(op.f('ix_availability_blocks_id'), table_name='availability_blocks')
    op.drop_index('idx_availability_blocks_user_time', table_name='availability_blocks')
    op.drop_index('idx_availability_blocks_time_range', table_name='availability_blocks')
    op.drop_table('availability_blocks')
    op.drop_index(op.f('ix_recurring_availability_id'), table_name='recurring_availability')
    op.drop_index('idx_recurring_availability_user', table_name='recurring_availability', postgresql_where=sa.text('enabled = TRUE'))
    op.drop_table('recurring_availability')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
